name: typecheck

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ts-typecheck:
    name: Type-Check
    if: ${{ github.actor != 'github-actions' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
      NODE_ENV: development
      npm_config_ignore_scripts: "true"
      ELECTRON_SKIP_BINARY_DOWNLOAD: "1"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      PUPPETEER_SKIP_DOWNLOAD: "1"
      npm_config_audit: "false"
      npm_config_fund: "false"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json

      - name: Setup npm 11.x
        run: |
          npm i -g npm@^11
          echo "Node: $(node -v)"
          echo "npm:  $(npm -v)"
          node -e "const v=require('child_process').execSync('npm -v').toString().trim(); if(!/^11\./.test(v)){process.exit(1)}"

      - name: Install deps (no scripts, no optional)
        run: npm ci --ignore-scripts --omit=optional

      - name: Run TypeScript type-check
        run: npm run typecheck
